### ISSUE TITLE
Unwanted spaces in translated file

### ISSUE THREAD

**Issue by TalviT** [LonamiWebs/Stringlate#107]
Stringlate sometimes places a space character between 'name' and '='.

Example:

Original: `<string name="share_comments">share comments</string>`
Translated: `<string name ="share_comments">Kommentare teilen</string>`

**Comment by Lonami** [comment]
Strange, because I literally replace the original string with the translated one, effectively [applying it as a template](https://github.com/LonamiWebs/Stringlate/blob/2c75d454cee1c45b54dc45f31f83186d0b2e0a13/src/app/src/main/java/io/github/lonamiwebs/stringlate/classes/resources/ResourcesParser.java#L639). Could you provide the name or link of the faulty application?

**Comment by TalviT** [comment]
The app is [diode](https://github.com/zagaberoo/diode) (an app for reddit), but I just noticed that the space was always in the same line, so i looked in the original 'strings.xml' file and there was that mistake too.

So Stringlate seems to work as it should and and I have opened the issue somewhat too quickly. Sorry for that.

**Comment by Lonami** [comment]
> Sorry for that.

No worries!
