### ISSUE TITLE
[Feature Request] Different branches

### ISSUE THREAD

**Issue by Lionirdeadman** [LonamiWebs/Stringlate#108]
I hope I'm not mistaking but I think Stringlate can't use another branch other than the default one (master in most cases). If I'm not, could this be an option?

**Comment by Lonami** [comment]
The library I use to clone repositories (which is highly outdated and it doesn't even seem to work with Android Studio 3.0, sigh…) should be able to switch between branches. So maybe it could be an option on the menu. Like "Advanced… > Switch branch" and a dialog would pop up with all the available ones.

**Comment by Lionirdeadman** [comment]
Yeah, that could work. Although maybe you could just long press on the repo and switch that way. Either way works. Thanks for answering so fast, haha.

**Comment by Lonami** [comment]
> Thanks for answering so fast

I'd live inside my computer if I could… Oh yeah let's keep this on topic.

**Comment by Lonami** [comment]
I was thinking that, for this, I would have to:
1. Scan for the resources on every possible branch because their location may be different
2. Restructure the files, and change it for something like "branch/locale" instead simply "locale".

So that's kind of hard. And in most case, unnecessary for a lot of users. I was thinking to add an option, "Prompt which branch to use when syncing resources", and if enabled, it would always ask *which* branch you want to use. Would this idea be okay, or do you still prefer to keep *all* the files with the strings around?

If the answer to the last question is to keep all files around, how should translations be handled? Be added to all of them? What if it's conflicting? Or what if a string you translated is not on the other branch?
