### ISSUE TITLE
0.9.13 crashes before cloning the repository

### ISSUE THREAD

**Issue by Bjornskjald** [LonamiWebs/Stringlate#121]
After clicking "start translating" app closes immediately...

**Comment by Bjornskjald** [comment]
Actually, after crash the chosen repo does show on the list, but without strings.xml file, updating that file also crash the app

**Comment by Lonami** [comment]
Could you please provide what repository is failing?

**Comment by Bjornskjald** [comment]
Well, on my device every repository is failing.

**Comment by Lonami** [comment]
Could you debug the application yourself? A stack trace would be really useful.

**Comment by Bjornskjald** [comment]
Found this: https://i.imgur.com/7BVAGGS.png

**Comment by Lonami** [comment]
Thank you, the fact that you use Polish + the error says "IllegalFormatPrecisionException" is actually really helpful. The translator for the Polish strings had a typo from `"%. 1f%%"` to the correct `"%.1f%%"`. Until the fix is available, you can switch to the English locale (or any other) and it should work!

**Comment by Lonami** [comment]
Running the `"Invalid format string"` inspection helps pinpoint these kind of errors, too.

**Comment by Bjornskjald** [comment]
So it was my fault... xD
Thanks

**Comment by Lonami** [comment]
> So it was my fault... xD

Whoops, didn't notice that haha. It's alright :P
