### ISSUE TITLE
Stringlate crashes, work gets lost

### ISSUE THREAD

**Issue by nikoss** [LonamiWebs/Stringlate#133]
Stringlate crashed. Oops. The strings you were translating, for the past half of an hour, were not saved (actually, I was translating for about 10 minutes). Too bad for you. There is no "session restore" or backup. You'll just have to do the translations, again.

Shouldn't Stringlate have an auto-backup or "session restore" function, just in case of a crash?

**Comment by Lonami** [comment]
Sorry to hear. Could you give steps to reproduce the crash, or provide a traceback? Stringlate saves to memory the changes as soon as you type a single character, but they're not flushed to disk until you actually switch to another locale, or leave the project you're translating. This is of course to avoid expensive IO calls for every single character the user types.

I will modify it to save every time you change to a different string, but we should fix that crash.

**Comment by nikoss** [comment]
For the specific crash
- I added the project https://github.com/IvanVolosyuk/diskusage
in Stringlate

- after diskusage was imported, I opened the project, and added a new locale by typing "el"

- then, I started translating, skipping a few strings

- 10 minutes or so into the translation Stringlate crashed

- in the meanwhile, I had other apps running (like Yandex Translate), and moved between these apps and Stringlate 

That's all I remember. Not very helpful, I guess.

**Comment by Lonami** [comment]
Yeah it's pretty weird that seemingly nothing triggered a crash. While typing some string? Some action that occurs when switching back? Not sure what it could be :(

**Comment by Peremptor** [comment]
Actually that was the thing I thought of immediately as I read "unless you are root you won't notice this". Why aren't the files saved on the SD card, where everyone can get them (and there's not only the app that can crash)?
Which sense does it make to hide the string.xml?
And here I am, thinking about IF I should give the app a try and the first issue making the worst case come true.

**Comment by Lonami** [comment]
> Why aren't the files saved on the SD card

Primarily because it's just more straightforward to access the local directory of the application, which I know will always work.

> and there's not only the app that can crash

I did not understand this part.

> Which sense does it make to hide the string.xml?

I never intended such thing, it's just, every application has its own data directory that will clean itself up if you uninstall the application. This wouldn't happen if I used the SD card where the normal user has access to. Users aren't supposed to edit the `.xml` themselves, that completely defeats the purpose of the application which is to abstract you from this!

*Even then*, I made available an option to export and import any added project as a `.zip` file, which contains the raw `.xml`, and all the information needed to recover the `.zip` into Stringlate.

> IF I should give the app a try

Well, why not? @nikoss' report about a seemingly random crash is the first report I'm aware of. It has never crashed like that for me, and of course I'm willing to fix this issue if I knew what happened. Furthermore, strings are now saved every time you press "Next" or "Previous", which should greatly reduce the risk of losing an important amount of work.

**Comment by nikoss** [comment]
@Peremptor maybe you misunderstood. In this particular crash, not all translations were lost. It is just, that the last translations were not saved (due to the crash). "The worst case" didn't come true.

And, of course, you can always export the .xml file 
(...and save it in your computer. At least, that is what I do).

**Comment by Lonami** [comment]
I'm cleaning up old issues. Please reopen this if you can consistently reproduce the bug (and give me steps) so that we can tackle it. https://github.com/LonamiWebs/Stringlate/commit/9bc8f00d177c333dad2348ae38647578b645c9c5 (linked above) should heavily alleviate any crash, but still, if I can reproduce a crash I'll try my best to fix it.
