### ISSUE TITLE
Hide strings nobody else has translated

### ISSUE THREAD

**Issue by Madis0** [LonamiWebs/Stringlate#152]
I'd like to see an option for Stringlate that would hide all strings that are not translated in other languages. 

A reason for that is that Stringlate seems to detect other files too, like arrays.xml, but they often don't contain values that need to be translated, at least in my experience.

**Comment by Lonami** [comment]
An option that would hide all strings that are not translated in other languages… So if a language has zero translations, it would show no strings at all? What would this be useful for?

> A reason for that is that Stringlate seems to detect other files too, like arrays.xml

Yes, this is a feature. Developers are free to use several files to keep their translations, for instance, `ui-strings.xml`, `message-strings.xml` and so on.

> but they often don't contain values that need to be translated

Strings or arrays flagged as `untranslatable="true"` in the XML are hidden in Stringlate because well, they're not meant to be translated. The best we can do is ask the developers to flag certain strings as untranslatable if they really are.

**Comment by Madis0** [comment]
>So if a language has zero translations, it would show no strings at all? What would this be useful for?

Well yeah, that's when user could disable it. Would be easy it was an quickly accessible option like show translated/identical strings. 

>Strings or arrays flagged as untranslatable="true" in the XML are hidden in Stringlate because well, they're not meant to be translated. 

I can see that support for strings, but I don't think many will bother to add that for other files...

**Comment by Lonami** [comment]
Again, what could this setting be useful for exactly?

**Comment by Madis0** [comment]
For easily hiding unnecessary strings, without bothering every single dev to add `untranslatable="true"` to all files.
Though maybe implementation-wise - as you suggested it can halter UX for new projects - it could instead be an option "Hide strings from files other than strings.xml"

**Comment by Lonami** [comment]
> without bothering every single dev to add `untranslatable="true"` to all files.

You and I know this should be the way to go though. Stringlate will even ignore files called `untranslatable.xml` or `do-not-translate.xml` or… a few others:
https://github.com/LonamiWebs/Stringlate/blob/84a564e5490f673ded2075dc515ee3fa2e84d85c/src/core/src/main/java/io/github/lonamiwebs/stringlate/classes/sources/GitSource.java#L31-L33

**Comment by Lonami** [comment]
Revisiting old issues, I'm closing this as I think this should be fixed on the default locale for the application in question. If nobody translates a string, then the developer (or someone through a PR, let them know with an issue) should fix the problem by flagging (or moving) the strings with "untranslatable".
