### ISSUE TITLE
Cannot select strings by ID, when all strings are translated. Also "Previous" & "Next" buttons are missing, then.

### ISSUE THREAD

**Issue by Olf0** [LonamiWebs/Stringlate#167]
Cannot select strings by ID, when all strings are translated (tested with Stringlate 0.11 under AOSP 4.1.2), see first screenshot below.
*Previous* and *Next* buttons are also missing, when all strings are already translated.
![screenshot_20171124_002](https://user-images.githubusercontent.com/16547876/33191496-107837c6-d0ba-11e7-97c6-27facde8f3f6.png)

Workaround: Use search (magnifying glass icon) to select a string.  Subsequently Stringlate looks and works as expected, see second screenshot.
![screenshot_20171124_003](https://user-images.githubusercontent.com/16547876/33191502-27cc63f2-d0ba-11e7-9033-838078c1e3d7.png)

**Comment by Lonami** [comment]
You should enable "Show translated strings" (or similar) from the menu. They're hidden by default so you can focus on translating the rest.

**Comment by Olf0** [comment]
> You should enable "Show translated strings" [...] from the menu. 

Well, I had this switched on (weeks ago).  Now I see, that this setting does not persist, when closing and reopening Stringlate; thus this turns out to be the real issue I am trying to address.
Side note: Thanks for pointing to this setting, as I forgot about it due to thinking, "I already configured Stringlate to my needs".

> They're hidden by default so you can focus on translating the rest.

I already assumed so, but it may make sense to set "Show translated strings" on by default, so newbies and occasional users of Stringlate will not be confused (as it happened to me).

Furthermore, this setting is somewhat buggy: When letting Stringlate open for a while, after switching "Show translated strings"  on, it is turned off and the "Previous" / "Next" buttons vanish again.  Technically this may also be solved by making this setting persistent.

**Comment by gr1sh** [comment]
Got the same problem on 7.1.2

**Comment by Lonami** [comment]
With the addition of the "done" button on commit https://github.com/LonamiWebs/Stringlate/commit/ff550dcd0c49615b6672d08ce3c9dec0e6f0809d, I think this is less necessary. Now instead showing empty it shows "Done!" and clicking that suggests to either export or "if you want to review some strings, click show translated". Not sure about the setting persisting for two reasons:
1. I'd like it to be easily accessible, and most people will open the menu while translating rather than the settings.
2. If it were to persist, since it's available while translating, it makes sense that the setting should apply to that repository.

Sorry for the delay. We can debate this further if you feel the need to do so.

**Comment by Olf0** [comment]
@Lonami, thanks for addressing this issue. 

> With the addition of the "done" button on commit ff550dc, I think this is less necessary.

Yes, I also believe this is sufficient to prevent users from getting helplessly stuck.
I personally would have preferred a persistent setting, but see the drawbacks, now that you pointed them out.

I suggest @gr1sh and me explore the new look & feel, when a new release is out and consider then, if this still poses an issue (presumably not).  Anyway, having dealt with and thought about this a couple of times while discussing this here, I suppose will not forget this setting anymore, hence the issue is solved in a non-technical way for me, already. ;)
