### ISSUE TITLE
Add ability to copy untranslated string to translated one

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#2]
Some words (mostly app names) should be kept the same, this will get rid of the hassle to rewrite them too.

**Comment by XyLoNaMiyX** [comment]
> Some words (mostly app names) should be kept the same

That's creators' choice. Currently, if a `<string …>` has the `translatable="false"` attribute, it will **not** be shown on the list of strings. However, a *Copy* button is not so hard to implement, and it might still be useful in some cases.

**Comment by licaon-kter** [comment]
Or allow selection in that field.

**Comment by XyLoNaMiyX** [comment]
> Or allow selection in that field.

I was surprised when it didn't work. I wish there was some `readonly="true"` attribute for `EditText`.

**Comment by XyLoNaMiyX** [comment]
Now you can select the text of the original string, which is a bit less intrusive than a whole new button.

**Comment by Madis0** [comment]
I would still vote for the button, it really helps in complex code strings, like HTML links. Similar to online services like Crowdin and Transifex, that let the user do both. 

The UX would be 
1. Tap a button that copies and selects the translation field
2. Modify text as needed 

Instead of current 
1. Select all the text (manually or with the option on Android 6+)
2. Hit copy 
3. Hold on the translation field 
4. Hit paste 
5. Focus the translation field 
6. Edit as needed

**Comment by Lonami** [comment]
Where should this button go then? Bear in mind not all screens are too large, and this extra button may easily become a problem when the keyboard is also shown, and the string spans accross a few lines. I wonder if it would be possible to modify the context menu of the original string field to include "Copy below" or something.

**Comment by Madis0** [comment]
Perhaps on the end of the label "Translated string", therefore also increasing the space between text fields. 

>I wonder if it would be possible to modify the context menu of the original string field to include "Copy below" or something.

Well, [there's this](https://medium.com/google-developers/custom-text-selection-actions-with-action-process-text-191f792d2999) but it seems to be way too global for this purpose.

**Comment by Lonami** [comment]
Let's get some issues closed shall we.
