### ISSUE TITLE
Bug: Stringlate adds additional escaping to Strings containing quotes

### ISSUE THREAD

**Issue by NotSoImportant** [LonamiWebs/Stringlate#209]
Example:

```
-    <string name="showPrevNextButtonsTitle">Zeige Schaltflächen "hoch"/"runter"</string>
+    <string name="showPrevNextButtonsTitle">Zeige Schaltflächen \"hoch\"/\"runter\"</string>
```

**Comment by Lonami** [comment]
This escaping is necessary. The original string was indeed "wrong".

**Comment by Lonami** [comment]
Quotes *inside* a string should be escaped, but they have a different meaning if they wrap a string entirely (from beginning to end, e.g. `<string ...>"some string"</string>`. Namely, it's made to support leading and trailing spaces. So you can do `<string ...>" some \"quoted\" string "</string>`.

Also it's a bit more complicated than that. HTML tags are taken into consideration so that attribute values are not escaped, e.g. `<a href="...">` will not escape the quotes. Thanks for taking the time to investigate so much into the application :P

**Comment by Lonami** [comment]
FWIW, unescaped quotes may also be used within the string to preserve whitespace:
![image](https://user-images.githubusercontent.com/6297805/39353627-8b4b94e4-4a08-11e8-963b-4d6d9e62e920.png)

Now this is getting tricky! How would we differentiate when it is a typo by the original developer and when it is intended?

**Comment by NotSoImportant** [comment]
My humble opinion?
Make Stringlate not care for what the developer maybe thought. Don't touch things that are not implicitly changed by the user.
If the original string is wrong that is not a problem of translation, but of the app development.

**Comment by Lonami** [comment]
Is this a problem with the translation or the original strings though? Look. The big deal here is that the translated format is lost. To support what you're suggesting, we would need to somehow merge the original translation style with the translated one, prefer to preserve the already-translated one, and then to keep the same order as the original translation, apply only new strings to the original style… Very complex! "What strings are new" is not even implemented at all. See #205 for that.
