### ISSUE TITLE
If first/last string remove previous/next button

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#36]
Might be a simple `xxx.setVisibility(View.GONE);` trick

**Comment by XyLoNaMiyX** [comment]
Better `View.HIDDEN` so the buttons' sizes remain the same. This will probably introduce some bugs like "Button not showing when blah blah blah", and I will blame you! Just kidding.

**Comment by MaxValue** [comment]
> This will probably introduce some bugs like "Button not showing when blah blah blah"
And it does! :D

On the last string, the button disappears, but the user cannot know that his/her changes are saved. Only if they go to "Previous" and then "Next" the string counter at the bottom updates (from Y/X to X/X) which gives a slight hint for this.

**Comment by Lonami** [comment]
> And it does

What's the use case that makes this bug appear?

> but the user cannot know that his/her changes are saved.

Pressing back should save the strings as well. Saving strings should be done transparently and the user should not worry about this at all if possible.

Also, sorry for the delay. Got busy with other projects.

**Comment by MaxValue** [comment]
Thanks for the reply!

It is not a bug, it is more of a UX issue. Usually apps have an icon (a checkmark or similar) or a toast message to indicate that the content was saved automatically. Just to clarify:

If i type something in (in the translation field) without pressing any button afterwards inside the app it is saved right away?

**Comment by Lonami** [comment]
No, as that would save too often. Only when leaving the activity and/or pressing previous/next.

**Comment by MaxValue** [comment]
Ah, i thought so. This is what i initially meant: The user cannot know currently when his work is "recorded". And the usual workflow is: Fill in, press next until strings are exhausted. So it could happen quite often for inexperienced users to either be confused or to exit the app (and therefore not saving the last string) or to go back to the menu, go to the project again in order to see if the string is still there.

A possible solution is to have a different button at the last string instead of next:

- "Finished!": this could open a prompt asking the user to export the strings or to go back to the project list to translate another project
- or "Next Language": this solution could open the language selection menu for this project right away

Of course, both of this solutions trigger a save behind the scenes.

Again, this is more of a look-and-feel issue. I can see that the current behaviour could generate confusion therefore reluctance to use the app (what we all don't want). Maybe i am exaggerating, so decide as you wish of course. You are the dev after all :)

**Comment by Lonami** [comment]
> to either be confused or to exit the app (and therefore not saving the last string)

But it would save the string. It's done automatically upon exiting the activity, by any event.

> * "Finished!": this could open a prompt asking the user to export the strings or to go back to the project list to translate another project

This button as an alternative to a "Next" on the last string does seem nice. It could guide new users into exporting their result.

**Comment by MaxValue** [comment]
> But it would save the string. It's done automatically upon exiting the activity, by any event.

I know, i know. It just does not feel right how it currently is. It's sort of comparable to the end of a train track where somebody forgot to build a train station or at least a bumper.

> It could guide new users into exporting their result.

Exactly my thoughts! I totally thought at the beginning that the strings get uploaded automatically. lel.
