### ISSUE TITLE
Show a confirmation dialog after selecting an app on Discover

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#50]
Open, discover, touch app...

Instead of just populating the repo url field and leaving the user wondering what to do next, why not better show a dialogue with "you will now download repo X to translate, you sure? Yes/no" and actually carry on?

**Comment by XyLoNaMiyX** [comment]
> why not better show a dialogue

Are you willing to make that dialog user-rotation-safe? I already have quite a few to fix!!

The real reason is because there isn't much more to it. Currently it's as fast as it could be. As I mentioned previously in some other issue, I thought of using some `ExpandableList` with buttons such as "Check" or "Add" (after clicking an item, it would *expand* to show these), to also check if the application is already translated in your locale or not. But other issues are above this on my list (not only by their relevance, but also by how easy they are).

**Comment by licaon-kter** [comment]
:) eh, the rotate man will show up

**Comment by XyLoNaMiyX** [comment]
> the rotate man will show up

Jokes apart, it's great to have spotted those bugs. For example, *Open camera* doesn't have them.

**Comment by Lonami** [comment]
Revisiting old issues, this didn't get much attention, so I guess people doesn't really mind. More straightforward to just tap once the application you want, and if you really don't like your choice, can always go back and not press "Start". Thanks for the suggestions though.
