### ISSUE TITLE
Auto download index

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#6]
Instead of showing that error "you don't have an index blahblah"

**Comment by XyLoNaMiyX** [comment]
You mean on the `Discover` activity? I decided it to be this way for two reasons:
- The user might be using a data connection rather than being connected to a network. The index is ~1MiB, undesirable in some cases.
- I thought that perhaps it would be a bit intrusive if the user got in the activity and suddenly saw a pop-up saying "Downloading index…". This dialog is cannot be canceled either.

Counter-arguments? Advantages/disadvantages?

**Comment by licaon-kter** [comment]
Ok, that makes sense. 

Now, the vanishing nature of a toast makes it not user friendly, can you add some text to that white empty view if no repos are downloaded, say "Repo index not dowloaded use the sync icon above" ?

**Comment by XyLoNaMiyX** [comment]
> the vanishing nature of a toast makes it not user friendly

I have to agree on that.

> can you add some text to that white empty view

That is a way nicer way to fix this problem. Will do I fix some other issues.
