### ISSUE TITLE
Wrong preselected locale

### ISSUE THREAD

**Issue by OffifialMITX** [LonamiWebs/Stringlate#67]
If you start translating an app, then close Stringlate, then reopen it and continue translating, after the second start the selected locale is the first in alphabetial order.

Shouldn't it be anyway better if only the original strings.xml was downloaded and anything else came in a pop up menu with every other strings file which is avalible + "add new locale"?

It would save your internet and disk space.

**Comment by XyLoNaMiyX** [comment]
> If you start translating an app, then close Stringlate, then reopen it and continue translating, after the second start the selected locale is the first in alphabetial order.

It works on the current upstream version, not yet available on F-Droid. I need to make a whole lot of changes to get things working again. But yes, I can confirm it's broken on the `v0.9.5` ([tiny silly mistake](https://github.com/LonamiWebs/Stringlate/compare/v0.9.5...master#diff-7327e57a92c4d98544906c8734e1b8feR753)).

> Shouldn't it be anyway better if only the original strings.xml was downloaded

Well, this is a bit hard. If I use the GitHub API then: **1.** I'm limited to GitHub-hosted projects and **2.** it won't work with applications that have a lot of strings (even if I only want the default, because the API won't return all the results). So I'm going to keep the clone-repository approach and avoid those two problems at once.

> It would save your internet and disk space.

Of course, you should clone the repository with an internet connection rather than using mobile data (unless you have unlimited or plenty to spare). But once cloned, no more internet access is required. And about the disk space, don't worry, it's only ~2KiB/`.xml`. If you *really* need it, you're free to delete the locales you don't want :)
