### ISSUE TITLE
Fails with 'Atarashii!'

### ISSUE THREAD

**Issue by drac0300** [LonamiWebs/Stringlate#68]
This app crashes when trying to download sources ofhttps://github.com/AnimaSA/Atarashii
I think it might be a string problem (caused by the '!' In the app name but I am not sure since I've not tested a lot)
Anyway, thanks for the cool app, and hoping this bug is resolved soon !

**Comment by drac0300** [comment]
That was a missclick

**Comment by drac0300** [comment]
I'll continue here :
This app crashes when trying to download sources ofhttps://github.com/AnimaSA/Atarashii
I think it might be a string problem (caused by the '!' In the app name but I am not sure since I've not tested a lot)
Anyway, thanks for the cool app, and hoping this bug is resolved soon !

**Comment by licaon-kter** [comment]
Use the EDIT function instead of new posts. ;)

**Comment by drac0300** [comment]
It's not available on the mobile github version, I'll try when I have my PC ^^'

**Comment by licaon-kter** [comment]
Use the "as desktop" option in your browser.

**Comment by XyLoNaMiyX** [comment]
The `AnimeNeko/Atarashii` repository works just fine on both the `v0.9.5` (available on F-Droid) and on the current `master` branch. What problem do you have exactly? Could you please be a bit more specific?

**Comment by drac0300** [comment]
Edited and cleaned up, sorry for the inconvenience 

Well, back to subject I do have 9.5 (from F-droid) but when I try to add the atarashii repository, it crashes at step "searching for strings.xml file"

**Comment by drac0300** [comment]
But if you don't get this error, it might be due to my esoteric setup... I just find it strange that it only is this repo.
Is there a way for me to get the logs ?

**Comment by licaon-kter** [comment]
Get Forkhub ;)

On topic: do detail your setup maybe.

**Comment by drac0300** [comment]
Hm hm, well I have Resurrection remix on a oneplus X with no Gapps but microG (root of course since I flashed a Rom). I also have Xposed with the Xprivacy module, but I don't think I've denied your app any permission...
As you see, not really vanilla android..

Didn't know about forkhub, looks quite good ! I will try it when I'm on wifi

**Comment by licaon-kter** [comment]
Try to clear this app's settings in Xprivacy so you are asked again.
Try to disable whitelist this app in Xprivacy.

**Comment by XyLoNaMiyX** [comment]
> Try to clear this app's settings in Xprivacy so you are asked again.
> Try to whitelist this app in Xprivacy, so it's not restricted at all.

Stringlate doesn't even require external storage access, it does it all in its own directory. If every other repository works, then it also has internet access. Does this repository work for you @licaon-kter?

**Comment by licaon-kter** [comment]
Did not get a chance to test, :(

**Comment by drac0300** [comment]
I tried after disabling xprivacy for stringlate and it still fails ><

**Comment by XyLoNaMiyX** [comment]
If you try going to https://github.com/AnimaSA/Atarashii from your browser, it will redirect you to https://github.com/AnimaNeko/Atarashii. This is the reason. Stringlate tries to reach to https://api.github.com/repos/AnimeSA/Atarashii, which doesn't exist. But for some reason, the API then follows the redirect and I don't update the entered URL anywhere else, it's considered to be correct, thus failing.

It would be nice if you could reach out to them and ask them to update their source code URL on F-Droid to reflect the name change, because eventually it will stop pointing to the correct place.

The repository is cloned correctly on the current `master` branch, so I will close this issue. I can't rely on the entered repository being from GitHub anymore (although these are still treated specially), and since these cases should not happen too often (I could maybe see if it's a GitHub repository and then make sure the entered URL is correct), I won't add any more code to handle it. Maybe I could explain these cases under the `/Help` Activity (any ideas?).

**Comment by XyLoNaMiyX** [comment]
By the way, if you want to translate the application from the `v0.9.5`, again, use https://github.com/AnimaNeko/Atarashii instead :)

**Comment by licaon-kter** [comment]
> It would be nice if you could reach out to them and ask them to update their source code URL on F-Droid to reflect the name change, because eventually it will stop pointing to the correct place.

https://gitlab.com/fdroid/fdroiddata/merge_requests/1955

**Comment by XyLoNaMiyX** [comment]
Thanks @licaon-kter :)
