### ISSUE TITLE
Search show obey the current view (untranslated only or all)

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#82]
Right now it will force `show translated` without user control or notice.

Maybe add a checkbox in the search view with `also check translated` and if that is on then toggle it on for the translation view.

**Comment by XyLoNaMiyX** [comment]
What about a different approach, maybe showing first the translated strings and then those missing a translation? Just like in the "Discover", installed applications show up first and then those which aren't installed.

My main idea was to use the search to find typos, and that's why it should (in my opinion) show all the strings, despite the setting being used.

**Comment by licaon-kter** [comment]
Yes, not sure if I have a better idea though

/closing for now
