### ISSUE TITLE
Search view, keep last term, add clear button

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#83]

**Comment by XyLoNaMiyX** [comment]
"keep last term"?

**Comment by licaon-kter** [comment]
Last search query, word.

**Comment by XyLoNaMiyX** [comment]
> Last search query, word(s).

I do find the "Clear button" useful, but not preserving the search. Since it's a different activity, I would have to save it under the settings (or similar), not only in memory for the current instance. I mean, can searches get _that_ sofisticated? Do you mean for the case where the user misclicks the incorrect string and they'd have to search it again?

**Comment by licaon-kter** [comment]
No, multiple results.
Now you have to write the search query, see 5 results, edit one, press search, write search query again,.... :(

**Comment by XyLoNaMiyX** [comment]
> edit one, press search, write search query

Now that makes more sense. Do you think the search should be conserved so the spinner on the Translate activity only showed those filtered strings? If so, how could we provide some feedback to the user so they knows not all the strings are shown because they're filtered?

**Comment by licaon-kter** [comment]
I guess preserving the search results might be trickier, I don't care, search them again.

You could select that text (and maybe raise the keyboard, although that makes it a bit annoying as you need to dismiss it).

That being said, 2 ideas:
* do not show any results if there is no search query (button for `show all` needed?)
* don't notify the user in any way, s/he has come here to search, so s/he should enter a query, right?

**Comment by XyLoNaMiyX** [comment]
> I guess preserving the search results might be trickier

Nah, that's as simple as preserving the search query, then show only those results. No need to preserve the results themselves.

> You could select that text (and maybe raise the keyboard, although that makes it a bit annoying as you need to dismiss it).

I did not understand this.

> do not show any results if there is no search query

I think it is useful to show the results, no matter what the query is. For example, an user might leave query empty to read the strings from that activity instead?

> don't notify the user in any way, s/he has come here to search

But I mean, since we'd be preserving/saving the query, _applying_ the query on the _Translate_ activity, not the _Search_ activity. In the very same way you can filter by "Show translated" or not, it would filter with that query.

Although perhaps my idea would be somewhat counter-intuitive ("if I was only looking for a string, why are more strings missing now?", that's why I wanted some feedback, like "this filter is currently applied")

**Comment by licaon-kter** [comment]
> applying the query on the Translate activity,

That's something else, I would like that (too) indeed.
That would need some sort of banner on top "Showing XXXX only" with a Dismiss/Showall button at the end.

But that is different, you would not be able to actually see the strings, and I like to see the strings/translation quick in one view in search, so it's a different/separate thing.

> I did not understand this.

Focus that text field, select the text, bring the keyboard on screen, so the user sees "hey this is now used, I can edit it, delete it, or not"

**Comment by XyLoNaMiyX** [comment]
> That would need some sort of banner on top "Showing XXXX only" with a Dismiss/Showall button at the end.

I thought it to be the title of the activity, but that would make no room for the `Dismiss` or `Clear search` buttons. So, where should that "banner" be shown? Above the "Selected locale" you say? I like the [snackbar](http://www.androidhive.info/wp-content/uploads/2015/09/android-snackbar-with-action-callback-undo.png), but sadly, that's more like a toast which should not stay there for long.

> so it's a different/separate thing.

It actually makes sense to implement them both in a row, since if I save the query to persist after the *Search* activity has been closed, it would also be accessible to the translate activity.

> Focus that text field, select the text

But the search text field is actually focused when you open the *Search* activity already, and the keyboard *is* shown. I still don't get your point 😓

**Comment by licaon-kter** [comment]
> I still don't get your point

Did not notice that, indeed they are.

**Comment by XyLoNaMiyX** [comment]
> some sort of banner on top "Showing XXXX only"

My two ideas are either:
<img width="320px" alt="option 1" src="https://cloud.githubusercontent.com/assets/6297805/22365552/6a6c21e0-e478-11e6-87b3-93b7b1009ac4.jpg" />
or
<img width="320px" alt="option 1" src="https://cloud.githubusercontent.com/assets/6297805/22365558/6fbf791c-e478-11e6-8d2c-d5c442ac58db.jpg" />

**Comment by licaon-kter** [comment]
First could be better as the title area might be small on some devices.
